// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDebq1GLHEXK2VI9UfAjxyPHn5pm24uqUA",
      authDomain: "flutter-project-b1e15.firebaseapp.com",
      databaseURL: "https://flutter-project-b1e15-default-rtdb.firebaseio.com",
      projectId: "flutter-project-b1e15",
      storageBucket: "flutter-project-b1e15.appspot.com",
      messagingSenderId: "388022158288",
      appId: "1:388022158288:web:a0324f28410019d80b2fd5"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvPnMOuEoJmOzYduPq0J7SMgGAKOhuGw',
    appId: '1:388022158288:android:a83b0b4d0905a11a0b2fd5',
    messagingSenderId: '388022158288',
    projectId: 'flutter-project-b1e15',
    storageBucket: 'flutter-project-b1e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdjjH9UwqWTEDg_kZMRX7PMxznfSWguyA',
    appId: '1:388022158288:ios:3c9ddd4f516638f00b2fd5',
    messagingSenderId: '388022158288',
    projectId: 'flutter-project-b1e15',
    storageBucket: 'flutter-project-b1e15.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdjjH9UwqWTEDg_kZMRX7PMxznfSWguyA',
    appId: '1:388022158288:ios:5b17caebc27603ae0b2fd5',
    messagingSenderId: '388022158288',
    projectId: 'flutter-project-b1e15',
    storageBucket: 'flutter-project-b1e15.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
